use_frameworks!

target 'RoktWebViewSDK_Example' do
  pod 'RoktWebViewSDK', :path => '../'

  target 'RoktWebViewSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 6.1.0'
    pod 'Nimble', '~> 11.2.2'
    pod 'FBSnapshotTestCase', '~> 2.1.4'
    pod 'Nimble-Snapshots', '~> 9.5.1'
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
