# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1
#------------------------------------------------------------
# executors
#------------------------------------------------------------
executors:
  rokt_xcode_11:
    macos:
      xcode: 11.7.0
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -o pipefail

#------------------------------------------------------------
# commands
#------------------------------------------------------------
commands:
  rokt_sync_bundler_and_fastlane:
    steps:
      - add_ssh_keys:
          fingerprints:
          - "6e:a1:7c:20:69:da:47:bd:c8:0e:c8:36:29:47:f0:4c"
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone 11 (13.6) [" || true
      - run:
          name: Fastlane Setup
          command: bundle exec fastlane setup

#------------------------------------------------------------
# jobs
#------------------------------------------------------------
jobs:
  build-run-unit-test:
    executor:
      name: rokt_xcode_11
    steps:
      - rokt_sync_bundler_and_fastlane
      - run:
          name: Fastlane
          command: bundle exec fastlane test
  publish:
    executor:
      name: rokt_xcode_11
    steps:
      - rokt_sync_bundler_and_fastlane
      #- run:
      #    name: Chat Notification
      #    when: on_success
      #    command: >
      #      curl --header "Content-Type: application/json"
      #      --request POST
      #      --data "{\"text\": \"*Mobile-iOS* is publishing _RoktWebViewSDK_ to CocoaPods\n${CIRCLE_BUILD_URL}\n_by ${CIRCLE_USERNAME}_\"}" 
      #      "${CHAT_WEBHOOK}&threadKey=${CIRCLE_BUILD_NUM}"
      #- run:
      #    name: Fastlane tag
      #    command: bundle exec fastlane tagRelease
      - run:
          name: Validate Pod
          command: pod spec lint --verbose
      - run:
          name: Push Pod
          command: pod trunk push
      - run:
          name: Chat Notification
          when: on_success
          command: >
            curl --header "Content-Type: application/json"
            --request POST
            --data "{\"text\": \"*Mobile-iOS* has published _RoktWebViewSDK_ to CocoaPods\"}" 
            "${CHAT_WEBHOOK}&threadKey=${CIRCLE_BUILD_NUM}"

#------------------------------------------------------------
# workflows
#------------------------------------------------------------
workflows:
  version: 2  
  building:
    jobs:
      - build-run-unit-test
      - hold:
          type: approval
          requires:
            - build-run-unit-test
      - publish